import '../styles/globals.scss'
import type { Metadata } from 'next'
import Panel from "../widgets/Panel/ui/Panel";

export const metadata: Metadata = {
  title: 'Company',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Panel/>
        {children}
      </body>
    </html>
  )
}
