import '../styles/globals.scss'
import type { Metadata } from 'next'
import Panel from "../widgets/Panel/ui/Panel";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: 'Company',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Panel/>
        {children}
        <div id="modal-portal"/>
      </body>
    </html>
  )
}
